trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"

stages:
  - stage: init
    displayName: "Version validation"
    lockBehavior: sequential
    jobs:
      - job: version
        displayName: Version calculation
        dependsOn: []
        steps:
          - checkout: self
            persistCredentials: true
            displayName: Checkout code

          - task: PowerShell@2
            displayName: Fetch tags
            inputs:
              targetType: "inline"
              script: git fetch --all --prune-tags --tags -v

  - stage: build
    dependsOn: init
    displayName: "Build"
    jobs:
      - job: build
        displayName: Build
        steps:
          - task: UseDotNet@2
            displayName: Ensure .NET 6.0
            inputs:
              packageType: "sdk"
              version: "6.0.x"

          - task: DotNetCoreCLI@2
            displayName: Restore projects
            inputs:
              command: "restore"
              projects: "src/**/*.csproj"
              feedsToUse: "select"
              vstsFeed: "TrainerHelper/TrainerFeed"

          - task: DotNetCoreCLI@2
            displayName: Build projects
            inputs:
              command: "build"
              projects: "src/**/*.csproj"
              arguments: "--no-restore"
