apiVersion: v1
kind: Service
metadata:
  labels:
    app: plans-api
  name: plans-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5003
  selector:
    app: plans-api
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plans-api-ingress
spec:
  rules:
    - host: traininghelperk8s-dns-hl4gzkfw.hcp.eastus.azmk8s.io # Twój wirtualny host
      http:
        paths:
          - path: /plans # Ścieżka URI
            pathType: Prefix
            backend:
              service:
                name: plans-api
                port:
                  number: 5003 # Port Twojego serwisu
