apiVersion: v1
kind: Service
metadata:
  labels:
    app: users-api
  name: users-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: users-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
    - host: traininghelperk8s-dns-hl4gzkfw.hcp.eastus.azmk8s.io # Twój wirtualny host
      http:
        paths:
          - path: /users-api # Ścieżka URI
            pathType: Prefix
            backend:
              service:
                name: users-api # Nazwa Twojej usługi API
                port:
                  number: 80 # Port usługi
